<?php

namespace app\models;

use yii\data\ActiveDataProvider;

class CustomerSearch extends Customer
{
    public $keyword;
    public $client_corporation_id;

    public function rules()
    {
        return [
            [['customer_code', 'name', 'keyword', 'client_corporation_id'], 'safe'],
        ];
    }

    public function attributeLabels()
    {
        $labels = parent::attributeLabels(); // TODO: Change the autogenerated stub
        $labels['keyword'] = 'キーワード';
        return $labels;
    }

    public function search($params)
    {
        $query = Customer::find()->alias('c')
            ->innerJoin('location l', 'c.location_id=l.location_id')
            ->innerJoin('bank_account ba', 'c.bank_account_id=ba.bank_account_id')
            ->leftJoin('phone p', 'c.customer_id=p.customer_id')
            ->leftJoin('mail_address ma', 'c.customer_id=ma.customer_id')
            ->where(['c.removed' => null]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        $this->load($params);
        if (!$this->validate()) {
            return $dataProvider;
        }

        $query
            ->andFilterWhere(['like', 'customer_code', $this->customer_code])
            ->andFilterWhere(['like', 'c.name', $this->name])
            ->andFilterWhere(['or',
                ['like', 'c.transfer_name', $this->keyword],
                ['like', 'c.memo', $this->keyword],
                ['like', 'ba.bank_name', $this->keyword],
                ['like', 'ba.branch_name', $this->keyword],
                ['like', 'l.address', $this->keyword],
                ['like', 'l.address_optional', $this->keyword],
                ['like', 'p.number_search', $this->keyword],
                ['like', 'ma.mail_address', $this->keyword]
            ]);

        return $dataProvider;
    }
}